- hosts: fileservers
  vars_files:
    - host_vars/vault_clear.yml
    - host_vars/vault_enc.yml
  vars:
    root_user_name: "root"
    root_user_group: "wheel"
    zfs_storage_pool: "zstore"
  tasks:
    - name: "Configure system clock, time, and time zone"
      ansible.builtin.include_role:
        name: ext/ans_role_config_time
    - name: "Configure OS security hardening options"
      ansible.builtin.include_role:
        name: ans_role_config_security_hardening
        public: true
    - name: "Configure system and package upgrades"
      ansible.builtin.include_role:
        name: ext/ans_role_config_upgrades
    - name: "Configure the FreeBSD 'loader' bootloader"
      ansible.builtin.include_role:
        name: ext/ans_role_config_loader
        public: true
    - name: "Install and configure the lsblk block-device info utility"
      ansible.builtin.include_role:
        name: ans_role_config_lsblk
        public: true
    - name: "Install and configure the smartmontools disk control and monitoring utility"
      ansible.builtin.include_role:
        name: ans_role_config_smartmontools
        public: true
    - name: "Install and configure ZFS hardware: disks, pools, vdevs, and devices"
      ansible.builtin.include_role:
        name: ans_role_config_zfs_hw
        public: true
      vars:
        cfg_zfs_hw_smartctl_cmd: "{{ smartmontools_main_cmd }}"
    - name: "Define a list of LAN NFS Shares, provided by various LAN hosts"
      ansible.builtin.include_role:
        name: ans_vars_lan_nfs_shares
        public: true
    - name: "Create and configure zfs filesystem datasets"
      ansible.builtin.include_role:
        name: ans_role_config_zfs_datasets
      vars:
        zfs_datasets_decrypt_at_boot: false
        zfs_datasets_to_create: >-
          {%- set results = [] -%}
          {%- for item in ans_vars_lan_nfs_shares_list if (item.hostname == inventory_hostname) -%}
          {%- set _ = results.append({
            'parent': zfs_storage_pool,
            'stem': item.share,
            'mnt': item.pmount ~ '/' ~ item.share,
            'mnt_inh': true,
            'owner': root_user_name,
            'group': root_user_group,
            'mode': '755',
            'enc': '',
            'nfs': true
          }) -%}
          {%- endfor -%}
          {{ results }}
    - name: "Install and configure the Network File System (NFS) server"
      ansible.builtin.include_role:
        name: ans_role_config_nfs_server
      vars:
        nfs_server_enable_nfsv3: false
        nfs_server_enable_nfsv4: true
    - name: "Configure cron jobs for all users"
      ansible.builtin.include_role:
        name: ans_role_config_cron
      vars:
        cfg_cron_jobs:
          - "{{ zfs_hw_scrub_all_pools_cron_job }}"
    - name: "Run all handlers"
      ansible.builtin.meta: flush_handlers
    - name: "Reboot the system, as required"
      ansible.builtin.include_role:
        name: ans_role_config_reboot
      vars:
        cfg_reboot_requests:
          - "{{ security_hardening_requests_reboot }}"
          - "{{ loader_requests_reboot }}"

